name: OSV Scanner

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  osv:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: google/osv-scanner-action@main
