name: Semgrep

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v5

      - uses: returntocorp/semgrep-action@v1
        with:
          config: auto
